apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-lab
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  encrypted: "true"
