apiVersion: v1
kind: List
items:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: gatewayclasses.gateway.networking.k8s.io
    spec:
      group: gateway.networking.k8s.io
      names:
        kind: GatewayClass
        plural: gatewayclasses
        singular: gatewayclass
        shortNames: ["gc"]
      scope: Cluster
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: gateways.gateway.networking.k8s.io
    spec:
      group: gateway.networking.k8s.io
      names:
        kind: Gateway
        plural: gateways
        singular: gateway
        shortNames: ["gw"]
      scope: Namespaced
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: httproutes.gateway.networking.k8s.io
    spec:
      group: gateway.networking.k8s.io
      names:
        kind: HTTPRoute
        plural: httproutes
        singular: httproute
        shortNames: ["hr"]
      scope: Namespaced
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: referencegrants.gateway.networking.k8s.io
    spec:
      group: gateway.networking.k8s.io
      names:
        kind: ReferenceGrant
        plural: referencegrants
        singular: referencegrant
      scope: Namespaced
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              x-kubernetes-preserve-unknown-fields: true
