apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-5min
  namespace: lab-jobs
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              image: curlimages/curl:8.10.1
              args: ["-sS", "http://api.lab-app.svc.cluster.local"]
